[features]
seeds = false
skip-lint = false
[programs.localnet]
oxylana = "EwmnkMvCVnCJt99M6K74NoSVSFCiSuceXMi2KeEYg1iD"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/home/zhaojie/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"
